import type { ImageSourcePropType } from 'react-native';

/**
 * Bundled letter-design artwork, by catalog key (shared/design-catalog.json). React Native needs
 * static `require` calls, so every catalog key is listed here; designAssets.test.ts fails when a
 * catalog key has no artwork. All current artwork is PROVISIONAL (generated by
 * tools/design-assets/generate_placeholders.py) and must be replaced or cleared before a
 * production build: release gate OPEN-14, licence record in assets/designs/ASSETS.md.
 */

/** Tileable texture overlays, drawn over the paper's base colour. */
export const PAPER_TEXTURES: Readonly<Record<string, ImageSourcePropType>> = {
  aged_cream: require('../../../assets/designs/papers/aged_cream.webp'),
  warm_ivory: require('../../../assets/designs/papers/warm_ivory.webp'),
  parchment: require('../../../assets/designs/papers/parchment.webp'),
};

/** Soft browning towards the edges, stretched over the whole sheet for every paper. */
export const EDGE_AGEING: ImageSourcePropType = require('../../../assets/designs/papers/edge_ageing.webp');

export const ELEMENT_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {
  stamp_dove: require('../../../assets/designs/stamps/stamp_dove.webp'),
  stamp_palm: require('../../../assets/designs/stamps/stamp_palm.webp'),
  stamp_lighthouse: require('../../../assets/designs/stamps/stamp_lighthouse.webp'),
  sticker_flower: require('../../../assets/designs/stickers/sticker_flower.webp'),
  sticker_moon: require('../../../assets/designs/stickers/sticker_moon.webp'),
  sticker_washi: require('../../../assets/designs/stickers/sticker_washi.webp'),
  postmark_round: require('../../../assets/designs/postmarks/postmark_round.webp'),
  postmark_wavy: require('../../../assets/designs/postmarks/postmark_wavy.webp'),
};
