-- pgTAP tests for public.blocks, public.connections, can_send() and their RPCs (Phase 5,
-- DEC-006/007/013). Run with `supabase test db` (CI: database.yml). no_plan() on purpose: written
-- without a local Postgres to count against.
--
-- IDs generated by RPCs (connection ids) are stashed in a temp table and read back via subqueries,
-- not psql's \gset: \gset should work here (pg_prove runs each file through psql), but its
-- interaction with variable interpolation *inside* the $$-quoted SQL strings that throws_ok()/
-- lives_ok() take as arguments is not something this file's author could verify without a local
-- Postgres, so it is avoided entirely in favor of plain, unambiguous SQL.
begin;

create extension if not exists pgtap with schema extensions;
select no_plan();

create temporary table test_ids (key text primary key, value uuid);
-- The owner (this session's initial role) creates and therefore owns this table; later `set local
-- role authenticated` blocks below still need to select/insert/update it directly, which the
-- table owner's default privileges do not extend to another role.
grant select, insert, update on test_ids to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Fixtures: four users (profiles created by the sign-up trigger)
-- ---------------------------------------------------------------------------------------------
insert into auth.users (id, email, raw_user_meta_data) values
  ('00000000-0000-0000-0000-000000000301', 'c1@example.test', '{}'),
  ('00000000-0000-0000-0000-000000000302', 'c2@example.test', '{}'),
  ('00000000-0000-0000-0000-000000000303', 'c3@example.test', '{}'),
  ('00000000-0000-0000-0000-000000000304', 'c4@example.test', '{}');

-- ---------------------------------------------------------------------------------------------
-- Structure and privileges
-- ---------------------------------------------------------------------------------------------
select ok((select relrowsecurity from pg_class where oid = 'public.blocks'::regclass), 'RLS is enabled on blocks');
select policies_are('public', 'blocks', array['blocks_select_own']::name[], 'blocks has exactly the expected policy');
select ok(not has_table_privilege('anon', 'public.blocks', 'select'), 'anon cannot read blocks');
select ok(has_table_privilege('authenticated', 'public.blocks', 'select'), 'authenticated can read blocks (rows limited by RLS)');
select ok(not has_table_privilege('authenticated', 'public.blocks', 'insert'), 'authenticated cannot write blocks directly (RPC only)');

select ok((select relrowsecurity from pg_class where oid = 'public.connections'::regclass), 'RLS is enabled on connections');
select policies_are('public', 'connections', array['connections_select_own']::name[], 'connections has exactly the expected policy');
select ok(not has_table_privilege('anon', 'public.connections', 'select'), 'anon cannot read connections');
select ok(has_table_privilege('authenticated', 'public.connections', 'select'), 'authenticated can read connections (rows limited by RLS)');
select ok(not has_table_privilege('authenticated', 'public.connections', 'insert'), 'authenticated cannot write connections directly (RPC only)');
select ok(not has_table_privilege('authenticated', 'public.connections', 'update'), 'authenticated cannot update connections directly');
select ok(not has_table_privilege('authenticated', 'public.connections', 'delete'), 'authenticated cannot delete connections directly');

select ok(not has_function_privilege('authenticated', 'public.is_blocked(uuid, uuid)', 'execute'), 'is_blocked is internal only');
select ok(not has_function_privilege('authenticated', 'public.can_send(uuid, uuid, uuid)', 'execute'), 'can_send is internal only (called from send_letter() and delivery, Phase 6)');
select ok(has_function_privilege('authenticated', 'public.block_user(uuid)', 'execute'), 'authenticated can call block_user');
select ok(has_function_privilege('authenticated', 'public.unblock_user(uuid)', 'execute'), 'authenticated can call unblock_user');
select ok(has_function_privilege('authenticated', 'public.request_connection(uuid)', 'execute'), 'authenticated can call request_connection');
select ok(has_function_privilege('authenticated', 'public.accept_connection(uuid)', 'execute'), 'authenticated can call accept_connection');
select ok(has_function_privilege('authenticated', 'public.decline_connection(uuid)', 'execute'), 'authenticated can call decline_connection');
select ok(has_function_privilege('authenticated', 'public.cancel_connection_request(uuid)', 'execute'), 'authenticated can call cancel_connection_request');
select ok(has_function_privilege('authenticated', 'public.remove_connection(uuid)', 'execute'), 'authenticated can call remove_connection');
select ok(not has_function_privilege('anon', 'public.request_connection(uuid)', 'execute'), 'anon cannot call request_connection');

-- ---------------------------------------------------------------------------------------------
-- can_send(): DEC-007's rule list, exercised directly (table owner bypasses the revoke, same as
-- every other internal-function test in this repo)
-- ---------------------------------------------------------------------------------------------
select ok(public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000301', null), 'a letter to yourself is always allowed');
select ok(not public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000999', null), 'sending to a nonexistent recipient is rejected');

-- Default receive_mode is invite_only (DEC-006) with no connection yet: rejected.
select ok(not public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'invite_only, no connection: rejected');

update public.profiles set receive_mode = 'everyone' where id = '00000000-0000-0000-0000-000000000302';
select ok(public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'everyone mode: allowed with no connection at all');
update public.profiles set receive_mode = 'invite_only' where id = '00000000-0000-0000-0000-000000000302';

insert into public.connections (requester_id, addressee_id, status, via, responded_at)
  values ('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', 'pending', 'request', null);
select ok(not public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'invite_only, pending connection: still rejected');
update public.connections set status = 'declined', responded_at = now()
  where requester_id = '00000000-0000-0000-0000-000000000301' and addressee_id = '00000000-0000-0000-0000-000000000302';
select ok(not public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'invite_only, declined connection: rejected');
update public.connections set status = 'accepted', responded_at = now()
  where requester_id = '00000000-0000-0000-0000-000000000301' and addressee_id = '00000000-0000-0000-0000-000000000302';
select ok(public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'invite_only, accepted connection: allowed');
select ok(public.can_send('00000000-0000-0000-0000-000000000302', '00000000-0000-0000-0000-000000000301', null), 'an accepted connection allows sending in either direction');
delete from public.connections where requester_id = '00000000-0000-0000-0000-000000000301' and addressee_id = '00000000-0000-0000-0000-000000000302';

insert into public.blocks (blocker_id, blocked_id) values ('00000000-0000-0000-0000-000000000302', '00000000-0000-0000-0000-000000000301');
update public.profiles set receive_mode = 'everyone' where id = '00000000-0000-0000-0000-000000000302';
select ok(not public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', null), 'blocked (even in everyone mode): rejected');
select ok(not public.can_send('00000000-0000-0000-0000-000000000302', '00000000-0000-0000-0000-000000000301', null), 'blocking is mutual: the blocker cannot send to the blocked user either');
update public.profiles set receive_mode = 'invite_only' where id = '00000000-0000-0000-0000-000000000302';
delete from public.blocks where blocker_id = '00000000-0000-0000-0000-000000000302' and blocked_id = '00000000-0000-0000-0000-000000000301';

-- Reply rule: a delivered letter from 302 to 301 lets 301 reply, even though 302 is invite_only
-- with no connection.
insert into public.letters (id, sender_id, recipient_id, status, delivered_at, body)
  values ('30000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000302',
          '00000000-0000-0000-0000-000000000301', 'delivered', now(), 'hi');
select ok(
  public.can_send('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000302', '30000000-0000-0000-0000-000000000001'),
  'replying to a delivered letter is allowed even without a connection'
);
select ok(
  not public.can_send('00000000-0000-0000-0000-000000000302', '00000000-0000-0000-0000-000000000301', '30000000-0000-0000-0000-000000000001'),
  'the reply exception only runs the direction it was received, not both'
);
select ok(
  not public.can_send('00000000-0000-0000-0000-000000000303', '00000000-0000-0000-0000-000000000302', '30000000-0000-0000-0000-000000000001'),
  'a letter id that was not received by the claimed sender does not grant the exception'
);

-- ---------------------------------------------------------------------------------------------
-- is_blocked()
-- ---------------------------------------------------------------------------------------------
insert into public.blocks (blocker_id, blocked_id) values ('00000000-0000-0000-0000-000000000303', '00000000-0000-0000-0000-000000000304');
select ok(public.is_blocked('00000000-0000-0000-0000-000000000303', '00000000-0000-0000-0000-000000000304'), 'is_blocked sees the blocker->blocked direction');
select ok(public.is_blocked('00000000-0000-0000-0000-000000000304', '00000000-0000-0000-0000-000000000303'), 'is_blocked sees the reverse direction too (mutual in effect)');
select ok(not public.is_blocked('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000304'), 'unrelated users are not blocked');
delete from public.blocks where blocker_id = '00000000-0000-0000-0000-000000000303';

-- ---------------------------------------------------------------------------------------------
-- As user 301: block_user / unblock_user
-- ---------------------------------------------------------------------------------------------
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;

select throws_ok($$ select public.block_user('00000000-0000-0000-0000-000000000301') $$, 'P0001', 'invalid_input', 'cannot block yourself');
select throws_ok($$ select public.block_user('00000000-0000-0000-0000-000000000999') $$, 'P0001', 'profile_not_found', 'cannot block a nonexistent user');
select lives_ok($$ select public.block_user('00000000-0000-0000-0000-000000000304') $$, 'blocking a real user succeeds');
select is((select count(*)::int from public.blocks where blocker_id = '00000000-0000-0000-0000-000000000301'), 1, 'the block row was created');
select lives_ok($$ select public.block_user('00000000-0000-0000-0000-000000000304') $$, 'blocking the same user twice is idempotent, not an error');
select is((select count(*)::int from public.blocks where blocker_id = '00000000-0000-0000-0000-000000000301'), 1, 'still exactly one block row');

select lives_ok($$ select public.unblock_user('00000000-0000-0000-0000-000000000304') $$, 'unblocking succeeds');
select is_empty($$ select 1 from public.blocks where blocker_id = '00000000-0000-0000-0000-000000000301' $$, 'the block row is gone');
select lives_ok($$ select public.unblock_user('00000000-0000-0000-0000-000000000304') $$, 'unblocking someone not blocked is not an error either');

reset role;

-- block_user removes an existing connection between the two users.
insert into public.connections (requester_id, addressee_id, status, via)
  values ('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000304', 'pending', 'request');
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000304","role":"authenticated"}', true);
set local role authenticated;
select lives_ok($$ select public.block_user('00000000-0000-0000-0000-000000000301') $$, 'blocking succeeds even with an existing connection');
select is_empty(
  $$ select 1 from public.connections where requester_id = '00000000-0000-0000-0000-000000000301' and addressee_id = '00000000-0000-0000-0000-000000000304' $$,
  'blocking deleted the pending connection between them (DEC-013)'
);
select lives_ok($$ select public.unblock_user('00000000-0000-0000-0000-000000000301') $$, 'cleanup: unblock');
reset role;

-- ---------------------------------------------------------------------------------------------
-- As user 301: request_connection and the full lifecycle (301 <-> 303)
-- ---------------------------------------------------------------------------------------------
-- set_config(..., true) ("is_local") lasts for the rest of this transaction, not just until the
-- next `reset role` - explicitly overwrite it to a claims object with no "sub" (matching
-- profiles.test.sql's proven pattern), rather than relying on the previous block's sub claim
-- having decayed on its own (it has not).
select set_config('request.jwt.claims', '{"role":"authenticated"}', true);
set local role authenticated;
select throws_ok(
  $$ select public.request_connection('00000000-0000-0000-0000-000000000303') $$,
  'P0001', 'not_authenticated', 'request_connection needs a signed-in user'
);
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;

select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000301') $$, 'P0001', 'invalid_input', 'cannot request a connection to yourself');
select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000999') $$, 'P0001', 'profile_not_found', 'cannot request a connection to a nonexistent user');

insert into test_ids (key, value) select 'req_301_303', public.request_connection('00000000-0000-0000-0000-000000000303');
select is(
  (select status::text from public.connections where id = (select value from test_ids where key = 'req_301_303')),
  'pending', 'a fresh request is pending'
);
select is(
  (select via::text from public.connections where id = (select value from test_ids where key = 'req_301_303')),
  'request', 'via is "request"'
);
select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000303') $$, 'P0001', 'already_pending', 'requesting the same pair again while pending is rejected');

reset role;

-- As user 303: accept
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000303","role":"authenticated"}', true);
set local role authenticated;
select throws_ok(
  $$ select public.accept_connection('00000000-0000-0000-0000-000000000001') $$, -- not a real connection id
  'P0001', 'not_found', 'accepting a nonexistent connection id is rejected'
);
select lives_ok(
  $$ select public.accept_connection((select value from test_ids where key = 'req_301_303')) $$,
  '303, the addressee, can accept'
);
select is(
  (select status::text from public.connections where id = (select value from test_ids where key = 'req_301_303')),
  'accepted', 'now accepted'
);
select ok(
  (select responded_at is not null from public.connections where id = (select value from test_ids where key = 'req_301_303')),
  'responded_at is set'
);
select throws_ok(
  $$ select public.accept_connection((select value from test_ids where key = 'req_301_303')) $$,
  'P0001', 'not_pending', 'accepting an already-accepted connection is rejected'
);
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000303') $$, 'P0001', 'already_connected', 'requesting a pair that is already connected is rejected');
select lives_ok(
  $$ select public.remove_connection((select value from test_ids where key = 'req_301_303')) $$,
  'either side can remove an accepted connection - 301, the requester, removes it'
);
select is_empty(
  $$ select 1 from public.connections where id = (select value from test_ids where key = 'req_301_303') $$,
  'the connection row is gone'
);
reset role;

-- ---------------------------------------------------------------------------------------------
-- Decline, cooldown, and cancel (301 <-> 304)
-- ---------------------------------------------------------------------------------------------
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
insert into test_ids (key, value) select 'req_301_304', public.request_connection('00000000-0000-0000-0000-000000000304');
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000304","role":"authenticated"}', true);
set local role authenticated;
select throws_ok(
  $$ select public.decline_connection('00000000-0000-0000-0000-000000000301') $$, -- wrong id (a user id, not a connection id, but any nonexistent id works)
  'P0001', 'not_found', 'declining a nonexistent connection id is rejected'
);
select lives_ok(
  $$ select public.decline_connection((select value from test_ids where key = 'req_301_304')) $$,
  '304, the addressee, can decline'
);
select is(
  (select status::text from public.connections where id = (select value from test_ids where key = 'req_301_304')),
  'declined', 'now declined'
);
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000304') $$, 'P0001', 'recently_declined', 'a fresh request within the 30-day cooldown is rejected');
reset role;

-- Simulate the cooldown having passed (table owner, direct update).
update public.connections set responded_at = now() - interval '31 days'
  where id = (select value from test_ids where key = 'req_301_304');

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
select lives_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000304') $$, 'after the cooldown, a fresh request replaces the old declined row');
select is(
  (select count(*)::int from public.connections
   where least(requester_id, addressee_id) = '00000000-0000-0000-0000-000000000301'
     and greatest(requester_id, addressee_id) = '00000000-0000-0000-0000-000000000304'),
  1, 'still exactly one row for the pair, now pending again'
);

update test_ids set value = (
  select id from public.connections
  where requester_id = '00000000-0000-0000-0000-000000000301' and addressee_id = '00000000-0000-0000-0000-000000000304'
) where key = 'req_301_304';

select throws_ok($$ select public.cancel_connection_request('00000000-0000-0000-0000-000000000001') $$, 'P0001', 'not_found', 'cancelling a nonexistent connection id is rejected');
select lives_ok(
  $$ select public.cancel_connection_request((select value from test_ids where key = 'req_301_304')) $$,
  '301, the requester, can cancel their own pending request'
);
select is_empty(
  $$ select 1 from public.connections where id = (select value from test_ids where key = 'req_301_304') $$,
  'the cancelled request is gone'
);
reset role;

-- ---------------------------------------------------------------------------------------------
-- The 20-pending cap (OPEN-5, provisional): 301 sends 20 requests, the 21st is rejected
-- ---------------------------------------------------------------------------------------------
do $$
declare
  i int;
  v_id uuid;
begin
  for i in 1..20 loop
    v_id := ('10000000-0000-0000-0000-0000000009' || lpad(i::text, 2, '0'))::uuid;
    insert into auth.users (id, email, raw_user_meta_data)
      values (v_id, 'cap' || i || '@example.test', '{}');
    insert into public.connections (requester_id, addressee_id, status, via)
      values ('00000000-0000-0000-0000-000000000301', v_id, 'pending', 'request');
  end loop;
end $$;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
select throws_ok(
  $$ select public.request_connection('00000000-0000-0000-0000-000000000302') $$,
  'P0001', 'too_many_pending', 'a 21st outstanding pending request is rejected (provisional cap, OPEN-5)'
);
reset role;

-- Cleanup: without this, 301 still has 20 outstanding pending requests and every later test that
-- has 301 call request_connection() again (unwrapped in throws_ok/lives_ok, since it is expected to
-- succeed) would throw unhandled and abort the rest of this file's transaction.
delete from public.connections
where requester_id = '00000000-0000-0000-0000-000000000301'
  and addressee_id in (
    select ('10000000-0000-0000-0000-0000000009' || lpad(i::text, 2, '0'))::uuid
    from generate_series(1, 20) as i
  );

-- ---------------------------------------------------------------------------------------------
-- Wrong-user rejections: only the addressee accepts/declines; only the requester cancels; only a
-- party removes (301 <-> 303, a fresh pair after the earlier one was removed)
-- ---------------------------------------------------------------------------------------------
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000301","role":"authenticated"}', true);
set local role authenticated;
insert into test_ids (key, value) select 'wrong_user', public.request_connection('00000000-0000-0000-0000-000000000303');
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000304","role":"authenticated"}', true); -- not a party to this connection
set local role authenticated;
select throws_ok(
  $$ select public.accept_connection((select value from test_ids where key = 'wrong_user')) $$,
  'P0001', 'not_found', 'a non-addressee cannot accept'
);
select throws_ok(
  $$ select public.decline_connection((select value from test_ids where key = 'wrong_user')) $$,
  'P0001', 'not_found', 'a non-addressee cannot decline'
);
select throws_ok(
  $$ select public.cancel_connection_request((select value from test_ids where key = 'wrong_user')) $$,
  'P0001', 'not_found', 'a non-requester cannot cancel'
);
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000303","role":"authenticated"}', true); -- the addressee, not the requester
set local role authenticated;
select throws_ok(
  $$ select public.cancel_connection_request((select value from test_ids where key = 'wrong_user')) $$,
  'P0001', 'not_found', 'the addressee cannot cancel (only the requester can)'
);
select lives_ok(
  $$ select public.accept_connection((select value from test_ids where key = 'wrong_user')) $$,
  'the real addressee accepts, for the remove test below'
);
reset role;

select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000304","role":"authenticated"}', true); -- still not a party
set local role authenticated;
select throws_ok(
  $$ select public.remove_connection((select value from test_ids where key = 'wrong_user')) $$,
  'P0001', 'not_found', 'a non-party cannot remove someone else''s connection'
);
reset role;

-- ---------------------------------------------------------------------------------------------
-- anon: no access at all
-- ---------------------------------------------------------------------------------------------
set local role anon;
select throws_ok($$ select * from public.blocks $$, '42501', null, 'anon cannot read blocks');
select throws_ok($$ select * from public.connections $$, '42501', null, 'anon cannot read connections');
select throws_ok($$ select public.block_user('00000000-0000-0000-0000-000000000301') $$, '42501', null, 'anon cannot block');
select throws_ok($$ select public.request_connection('00000000-0000-0000-0000-000000000301') $$, '42501', null, 'anon cannot request a connection');
reset role;

select * from finish();
rollback;
