import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useDeferredValue, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Pressable, ScrollView, useWindowDimensions } from 'react-native';

import { AppText } from '@/components/AppText';
import { Button } from '@/components/Button';
import { DirectionalIcon } from '@/components/DirectionalIcon';
import { currentLanguage } from '@/core/i18n';
import { formatDate, formatNumber } from '@/core/i18n/format';
import { MIN_TOUCH_TARGET } from '@/core/theme/tokens';
import { useTheme } from '@/core/theme/useTheme';
import { isLayoutRtl } from '@/core/i18n/direction';
import { getDraftsRepository } from '@/data/letters/draftsRepository';
import { getLettersRepository } from '@/data/letters/lettersRepository';
import { detectBodyDirection } from '@/domain/bodyDirection';
import { CANVAS_WIDTH } from '@/features/designs/LetterCanvas';
import { defaultDesign, readDesign, type Design } from '@/domain/design';
import { LETTER_BODY_MAX, shouldShowBodyCounter } from '@/domain/letterLimits';
import { defaultScheduleTime, validateScheduleTime } from '@/domain/schedule';
import { DeskSheet, DeskToolbar, type DeskMode } from '@/features/compose/LetterDesk';
import { letterErrorKey, type TranslatedLetterError } from '@/features/letters/letterErrors';
import { SchedulePicker } from '@/features/letters/SchedulePicker';

const AUTOSAVE_DEBOUNCE_MS = 600;

/**
 * Draft editor (the "desk", Phase 12): the letter sheet is the writing surface (subject and body
 * typed on the paper), with a sticky Paper / Write / Decorate toolbar above it; autosaved locally.
 * Also the recipient picker (Phase 5), Send (Phase 6 M2) and
 * Schedule (M3: an inline SchedulePicker; same send path with a time). The route id is generated by the caller (drafts list "+ New draft", or an existing
 * draft's own id) so autosave always has somewhere to write from the very first keystroke.
 *
 * Send/Schedule: confirm first (a delivered letter cannot be changed), then (for a schedule,
 * re-check the time before the dialog and again after it: time passes while picking) save exactly
 * what is on screen, push that draft so the server copy matches, send_letter,
 * then drop the local copy only (the server row is no longer a draft). Autosave is blocked from the
 * moment Send is pressed so a late save cannot recreate a local draft for a letter already sent.
 */
export default function ComposeScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { t } = useTranslation();
  const { colors, spacing } = useTheme();
  const window = useWindowDimensions();
  const router = useRouter();

  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [design, setDesign] = useState<Design>(defaultDesign());
  // False when the stored design is newer than this app: shown, never overwritten (DEC-060 (4)).
  const [designEditable, setDesignEditable] = useState(true);
  const storedDesign = useRef<unknown>(null);
  const [mode, setMode] = useState<DeskMode>('write');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const scrollY = useRef(0);
  const sheet = useRef({ y: 0, width: CANVAS_WIDTH });
  const [openedAt] = useState(() => Date.now());
  const [recipientId, setRecipientId] = useState<string | null>(null);
  // A reply's recipient is fixed (the server requires the parent letter's sender).
  const [isReply, setIsReply] = useState(false);
  const [loaded, setLoaded] = useState(false);
  // Whether this draft exists in the local store yet. A brand-new draft is only written once it
  // has some content, so opening "New draft" and backing out leaves nothing behind (phone QA).
  const [stored, setStored] = useState(false);
  const [saving, setSaving] = useState(false);
  const [sending, setSending] = useState(false);
  const [sendError, setSendError] = useState<TranslatedLetterError | 'unknown' | null>(null);
  const [scheduleAt, setScheduleAt] = useState<Date | null>(null);
  const sendingRef = useRef(false);
  const autosaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // The save waiting on the debounce, if any. Leaving the screen runs it at once instead of
  // dropping it: typing and going straight back lost the last edits (Maestro run on the phone).
  const pendingSave = useRef<(() => void) | null>(null);
  const deletedRef = useRef(false);

  useEffect(() => {
    let cancelled = false;
    void getDraftsRepository()
      .get(id)
      .then((draft) => {
        if (cancelled) return;
        if (draft) {
          setStored(true);
          setSubject(draft.subject ?? '');
          setBody(draft.body);
          const read = readDesign(draft.design);
          storedDesign.current = draft.design;
          setDesign(read.design);
          setDesignEditable(read.editable);
          setRecipientId(draft.recipientId);
          setIsReply(Boolean(draft.parentLetterId));
        }
        setLoaded(true);
      });
    return () => {
      cancelled = true;
    };
  }, [id]);

  // The recipient picker (a separate screen) writes to the same draft id; re-read on return, so
  // a change made there shows up here without waiting for this screen's own autosave.
  useFocusEffect(
    useCallback(() => {
      void getDraftsRepository()
        .get(id)
        .then((draft) => {
          if (draft) {
            setStored(true);
            setRecipientId(draft.recipientId);
          }
        });
    }, [id]),
  );

  /** What to save as the design: never this app's version of a design it cannot represent. */
  const designToSave = () => (designEditable ? design : storedDesign.current);

  // Flush a debounced save when the screen loses focus (back, or opening a picker).
  useFocusEffect(
    useCallback(
      () => () => {
        const save = pendingSave.current;
        if (!save || sendingRef.current || deletedRef.current) return;
        if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
        save();
      },
      [],
    ),
  );

  useEffect(() => {
    if (!loaded) return; // do not autosave while the initial load is still in flight
    if (sendingRef.current || deletedRef.current) return; // see the Send note in the header comment
    if (
      !stored &&
      !subject.trim() &&
      !body.trim() &&
      recipientId === null &&
      design.elements.length === 0
    )
      return;
    const run = () => {
      pendingSave.current = null;
      setSaving(true);
      void getDraftsRepository()
        .save({
          id,
          subject: subject.trim() ? subject : null,
          body,
          design: designToSave(),
          recipientId,
        })
        .then(() => setStored(true))
        .finally(() => setSaving(false));
    };
    pendingSave.current = run;
    const timer = setTimeout(run, AUTOSAVE_DEBOUNCE_MS);
    autosaveTimer.current = timer;
    return () => clearTimeout(timer);
    // Autosave fires only when subject/body/design/recipientId actually change; `loaded` just
    // gates the first run.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [subject, body, design, recipientId, loaded]);

  const canSend = loaded && recipientId !== null && body.trim() !== '' && !sending;

  // Live hint while picking; onSend re-checks against the clock at the moment of sending.
  const scheduleProblem = scheduleAt ? validateScheduleTime(scheduleAt, new Date()) : null;

  async function onSend(scheduledAt: Date | null = null) {
    if (sendingRef.current) return;
    if (scheduledAt) {
      const problem = validateScheduleTime(scheduledAt, new Date());
      if (problem) {
        setSendError(problem);
        return;
      }
    }
    sendingRef.current = true;
    if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
    pendingSave.current = null;
    setSending(true);
    setSendError(null);
    try {
      const drafts = getDraftsRepository();
      await drafts.save({
        id,
        subject: subject.trim() ? subject : null,
        body,
        design: designToSave(),
        recipientId,
      });
      await drafts.push(id);
      await getLettersRepository().sendLetter(id, scheduledAt);
      await drafts.forgetLocal(id);
      router.replace({ pathname: '/sent', params: { view: scheduledAt ? 'scheduled' : 'sent' } });
    } catch (error) {
      sendingRef.current = false;
      setSending(false);
      setSendError(letterErrorKey(error));
    }
  }

  /** Asks before sending; a scheduled time is shown in full so the user sees exactly when. */
  function confirmSend(scheduledAt: Date | null = null) {
    if (scheduledAt) {
      const problem = validateScheduleTime(scheduledAt, new Date());
      if (problem) {
        setSendError(problem);
        return;
      }
    }
    const title = scheduledAt ? t('compose.scheduleConfirmTitle') : t('compose.sendConfirmTitle');
    const message = scheduledAt
      ? t('compose.scheduleConfirmMessage', {
          when: formatDate(scheduledAt, currentLanguage(), {
            weekday: 'long',
            day: 'numeric',
            month: 'long',
            year: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
          }),
        })
      : t('compose.sendConfirmMessage');
    Alert.alert(title, message, [
      { text: t('compose.sendConfirmCancel'), style: 'cancel' },
      {
        text: scheduledAt ? t('compose.scheduleConfirm') : t('compose.send'),
        onPress: () => void onSend(scheduledAt),
      },
    ]);
  }

  function onDelete() {
    Alert.alert(t('compose.deleteConfirmTitle'), t('compose.deleteConfirmMessage'), [
      { text: t('compose.deleteConfirmCancel'), style: 'cancel' },
      {
        text: t('compose.deleteConfirmConfirm'),
        style: 'destructive',
        onPress: () => {
          // Like Send: nothing may save this draft again, or leaving would re-create it.
          deletedRef.current = true;
          if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
          pendingSave.current = null;
          void getDraftsRepository().remove(id).then(router.back);
        },
      },
    ]);
  }

  // Live, not read back from the saved draft: the preview must reflect what is on screen right
  // now, not the last debounced save (PLAN §3.5's body_dir fallback is the sender's UI direction).
  // The preview (and its direction) follow a deferred copy of the text, so with a long letter a
  // keystroke updates the input first and the full re-layout of the preview never blocks typing.
  const previewBody = useDeferredValue(body);
  const bodyDir = detectBodyDirection(previewBody, isLayoutRtl() ? 'rtl' : 'ltr');

  return (
    <ScrollView
      testID="compose-screen"
      // The desk toolbar (third child) stays on screen while the letter scrolls under it.
      stickyHeaderIndices={[2]}
      scrollEventThrottle={32}
      onScroll={(e) => {
        scrollY.current = e.nativeEvent.contentOffset.y;
      }}
      contentContainerStyle={{ padding: spacing.lg, gap: spacing.md, flexGrow: 1 }}
      style={{ backgroundColor: colors.background }}
    >
      <Pressable
        testID="compose-back"
        accessibilityRole="button"
        onPress={() => router.back()}
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: spacing.xs,
          minHeight: MIN_TOUCH_TARGET,
        }}
      >
        <DirectionalIcon name="chevron-back" size={18} color={colors.primary} />
        <AppText style={{ color: colors.primary }}>{t('tabs.drafts')}</AppText>
      </Pressable>
      {isReply ? (
        <AppText testID="compose-reply-recipient" variant="muted">
          {t('compose.replyRecipient')}
        </AppText>
      ) : (
        <Pressable
          testID="compose-recipient-row"
          accessibilityRole="button"
          onPress={() => router.push({ pathname: '/compose/pick-recipient', params: { id } })}
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            gap: spacing.xs,
            minHeight: MIN_TOUCH_TARGET,
          }}
        >
          <AppText variant="muted">{t('compose.recipientLabel')}: </AppText>
          <AppText style={{ color: recipientId ? colors.text : colors.primary, flex: 1 }}>
            {recipientId ? t('compose.recipientChosen') : t('compose.noRecipient')}
          </AppText>
          <DirectionalIcon name="chevron-forward" size={16} color={colors.textMuted} />
        </Pressable>
      )}
      <DeskToolbar
        testID="compose"
        design={design}
        onDesignChange={setDesign}
        designEditable={designEditable}
        mode={mode}
        onModeChange={setMode}
        selectedId={selectedId}
        onSelect={setSelectedId}
        bodyDir={bodyDir}
        getVisibleCenterY={() => {
          // The middle of the screen, in sheet-width units from the top of the sheet.
          const { y, width } = sheet.current;
          return Math.max(0.15, (scrollY.current + window.height / 2 - y) / Math.max(1, width));
        }}
      />
      <DeskSheet
        testID="compose"
        design={design}
        mode={mode}
        selectedId={selectedId}
        onSelect={setSelectedId}
        onWantWrite={() => {
          setMode('write');
          setSelectedId(null);
        }}
        subject={subject}
        body={body}
        onSubjectChange={setSubject}
        onBodyChange={setBody}
        bodyDir={bodyDir}
        postmarkDate={new Date(openedAt)}
        onSheetLayout={(layout) => {
          sheet.current = layout;
        }}
      />
      {shouldShowBodyCounter(body.length) ? (
        <AppText testID="compose-body-counter" variant="muted" accessibilityLiveRegion="polite">
          {t('compose.bodyCounter', {
            used: formatNumber(body.length, currentLanguage()),
            max: formatNumber(LETTER_BODY_MAX, currentLanguage()),
          })}
        </AppText>
      ) : null}
      {saving ? (
        <AppText testID="compose-saving" variant="muted">
          {t('compose.saving')}
        </AppText>
      ) : null}

      {sendError ? (
        <AppText testID="compose-send-error" style={{ color: colors.danger }}>
          {t(`letters.error.${sendError}`)}
        </AppText>
      ) : null}
      {scheduleAt ? (
        <>
          <SchedulePicker
            testID="compose-schedule-picker"
            value={scheduleAt}
            onChange={(next) => {
              setScheduleAt(next);
              setSendError(null);
            }}
            language={currentLanguage()}
          />
          {scheduleProblem ? (
            <AppText testID="compose-schedule-problem" style={{ color: colors.danger }}>
              {t(`letters.error.${scheduleProblem}`)}
            </AppText>
          ) : null}
          <Button
            testID="compose-schedule-confirm"
            title={t('compose.scheduleConfirm')}
            loading={sending}
            disabled={!canSend || scheduleProblem !== null}
            onPress={() => confirmSend(scheduleAt)}
          />
          <Button
            testID="compose-schedule-cancel"
            title={t('compose.scheduleCancel')}
            variant="secondary"
            disabled={sending}
            onPress={() => {
              setScheduleAt(null);
              setSendError(null);
            }}
          />
        </>
      ) : (
        <>
          <Button
            testID="compose-send"
            title={t('compose.send')}
            loading={sending}
            disabled={!canSend}
            onPress={() => confirmSend()}
          />
          <Button
            testID="compose-schedule-open"
            title={t('compose.scheduleOpen')}
            variant="secondary"
            disabled={sending}
            onPress={() => {
              setScheduleAt(defaultScheduleTime(new Date()));
              setSendError(null);
            }}
          />
        </>
      )}
      <Button
        testID="compose-delete"
        title={t('compose.delete')}
        variant="secondary"
        onPress={onDelete}
      />
    </ScrollView>
  );
}
