import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Pressable, ScrollView, TextInput } from 'react-native';

import { AppText } from '@/components/AppText';
import { Button } from '@/components/Button';
import { DirectionalIcon } from '@/components/DirectionalIcon';
import { useTheme } from '@/core/theme/useTheme';
import { isLayoutRtl } from '@/core/i18n/direction';
import { getDraftsRepository } from '@/data/letters/draftsRepository';
import { detectBodyDirection } from '@/domain/bodyDirection';
import { defaultDesign, normalizeDesign, type Design } from '@/domain/design';
import { LetterRenderer } from '@/features/designs/LetterRenderer';

const AUTOSAVE_DEBOUNCE_MS = 600;

/**
 * Draft editor: subject + body, autosaved locally, plus a live LetterRenderer preview and a link
 * to the design picker (Phase 4). Recipient/schedule pickers are Phase 5/6. The route id is
 * generated by the caller (drafts list "+ New draft", or an existing draft's own id) so autosave
 * always has somewhere to write from the very first keystroke.
 */
export default function ComposeScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { t } = useTranslation();
  const { colors, spacing, fontSize } = useTheme();
  const router = useRouter();

  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [design, setDesign] = useState<Design>(defaultDesign());
  const [recipientId, setRecipientId] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let cancelled = false;
    void getDraftsRepository()
      .get(id)
      .then((draft) => {
        if (cancelled) return;
        if (draft) {
          setSubject(draft.subject ?? '');
          setBody(draft.body);
          setDesign(normalizeDesign(draft.design));
          setRecipientId(draft.recipientId);
        }
        setLoaded(true);
      });
    return () => {
      cancelled = true;
    };
  }, [id]);

  // The design and recipient pickers (separate screens) write to the same draft id; re-read on
  // return, so a change made there shows up here without waiting for this screen's own autosave.
  useFocusEffect(
    useCallback(() => {
      void getDraftsRepository()
        .get(id)
        .then((draft) => {
          if (draft) {
            setDesign(normalizeDesign(draft.design));
            setRecipientId(draft.recipientId);
          }
        });
    }, [id]),
  );

  useEffect(() => {
    if (!loaded) return; // do not autosave while the initial load is still in flight
    const timer = setTimeout(() => {
      setSaving(true);
      void getDraftsRepository()
        .save({
          id,
          subject: subject.trim() ? subject : null,
          body,
          design,
          recipientId,
        })
        .finally(() => setSaving(false));
    }, AUTOSAVE_DEBOUNCE_MS);
    return () => clearTimeout(timer);
    // Autosave fires only when subject/body/design/recipientId actually change; `loaded` just
    // gates the first run.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [subject, body, design, recipientId, loaded]);

  function onDelete() {
    Alert.alert(t('compose.deleteConfirmTitle'), t('compose.deleteConfirmMessage'), [
      { text: t('compose.deleteConfirmCancel'), style: 'cancel' },
      {
        text: t('compose.deleteConfirmConfirm'),
        style: 'destructive',
        onPress: () => void getDraftsRepository().remove(id).then(router.back),
      },
    ]);
  }

  // Live, not read back from the saved draft: the preview must reflect what is on screen right
  // now, not the last debounced save (PLAN §3.5's body_dir fallback is the sender's UI direction).
  const bodyDir = detectBodyDirection(body, isLayoutRtl() ? 'rtl' : 'ltr');

  return (
    <ScrollView
      testID="compose-screen"
      contentContainerStyle={{ padding: spacing.lg, gap: spacing.md, flexGrow: 1 }}
      style={{ backgroundColor: colors.background }}
    >
      <Pressable
        testID="compose-back"
        accessibilityRole="button"
        onPress={() => router.back()}
        style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}
      >
        <DirectionalIcon name="chevron-back" size={18} color={colors.primary} />
        <AppText style={{ color: colors.primary }}>{t('tabs.drafts')}</AppText>
      </Pressable>
      <Pressable
        testID="compose-recipient-row"
        accessibilityRole="button"
        onPress={() => router.push({ pathname: '/compose/pick-recipient', params: { id } })}
        style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}
      >
        <AppText variant="muted">{t('compose.recipientLabel')}: </AppText>
        <AppText style={{ color: recipientId ? colors.text : colors.primary, flex: 1 }}>
          {recipientId ? t('compose.recipientChosen') : t('compose.noRecipient')}
        </AppText>
        <DirectionalIcon name="chevron-forward" size={16} color={colors.textMuted} />
      </Pressable>
      <TextInput
        testID="compose-subject"
        accessibilityLabel={t('compose.subjectLabel')}
        placeholder={t('compose.subjectLabel')}
        placeholderTextColor={colors.textMuted}
        value={subject}
        onChangeText={setSubject}
        style={{ fontSize: fontSize.lg, color: colors.text, textAlign: 'auto' }}
      />
      <TextInput
        testID="compose-body"
        accessibilityLabel={t('compose.bodyLabel')}
        placeholder={t('compose.bodyLabel')}
        placeholderTextColor={colors.textMuted}
        value={body}
        onChangeText={setBody}
        multiline
        style={{
          flex: 1,
          minHeight: 160,
          fontSize: fontSize.md,
          color: colors.text,
          textAlign: 'auto',
        }}
      />
      {saving ? (
        <AppText testID="compose-saving" variant="muted">
          {t('compose.saving')}
        </AppText>
      ) : null}

      <LetterRenderer
        testID="compose-preview"
        design={design}
        subject={subject}
        body={body}
        bodyDir={bodyDir}
      />
      <Button
        testID="compose-change-design"
        title={t('compose.changeDesign')}
        variant="secondary"
        onPress={() => router.push({ pathname: '/compose/pick-design', params: { id } })}
      />

      <Button
        testID="compose-delete"
        title={t('compose.delete')}
        variant="secondary"
        onPress={onDelete}
      />
    </ScrollView>
  );
}
